## 50 câu hỏi ngắn về Numpy

### Câu hỏi 1: import numpy dưới bí danh np và xem phiên bản

In [2]:
import numpy as np

print(np.__version__)

1.26.2


### Câu hỏi 2: Làm thế nào để tạo mảng 1 chiều?

In [ ]:
arr1d = np.array([1, 2, 3, 4, 5])

### Câu hỏi 3: Làm thế nào để tạo một mảng boolean?

In [ ]:
arrBool = np.array([True, False, True, False, True])

In [3]:
arrBool = np.random.randint(0, 2, size=5).astype(bool)

In [5]:
arr1d = np.array([1, 2, 3, 4, 5])
arrBool = arr1d > 3
print(arrBool)

[False False False  True  True]


In [ ]:
arrBool_True = np.ones(5, dtype=bool)
arrBool_False = np.zeros(5, dtype=bool)

### Câu hỏi 4: Làm thế nào để trích xuất các mục thỏa mãn một điều kiện nhất định từ mảng 1 chiều?
Ví dụ: Trích xuất tất cả các số lẻ từ mảng

In [ ]:
arr1d = np.random.randint(1, 10, size=10)
arrOdd = np.array([])
for i in range(len(arr1d)):
    if arr1d[i] % 2 != 0:
        arrOdd = np.append(arrOdd, arr1d[i])

[1. 9. 1. 7. 5.]
[8 1 8 4 6 9 1 7 5 6]


### Câu hỏi 5: Làm thế nào để thay thế các mục thỏa mãn một điều kiện bằng một giá trị khác trong mảng numpy?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1

In [13]:
arr1d = np.random.randint(1, 10, size=10)
for i in range(len(arr1d)):
    if arr1d[i] % 2 != 0:
        arr1d[i] = -1

### Câu hỏi 6: Làm thế nào để thay thế các mục thỏa mãn một điều kiện mà không ảnh hưởng đến mảng ban đầu?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1 mà không thay đổi arr

In [ ]:
arr1d = np.random.randint(1, 10, size=10)
arr1d_copy = arr1d.copy()
for i in range(len(arr1d_copy)):
    if arr1d_copy[i] % 2 != 0:
        arr1d_copy[i] = -1

### Câu hỏi 7: Làm thế nào để định hình lại một mảng?

In [ ]:
arr = np.arange(1, 21).reshape(4, 5)

### Câu hỏi 8: Làm thế nào để xếp chồng hai mảng theo chiều dọc?

In [17]:
arr1 = np.arange(1, 11).reshape(2, 5)
arr2 = np.arange(11, 21).reshape(2, 5)
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Câu hỏi 9: Làm thế nào để xếp chồng hai mảng theo chiều ngang?

In [15]:
arr1 = np.arange(1, 11).reshape(2, 5)
arr2 = np.arange(11, 21).reshape(2, 5)
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


### Câu hỏi 10: Làm thế nào để tạo các chuỗi tùy chỉnh trong numpy mà không cần mã hóa cứng?
Ví dụ: 
Input: a = np.array([1,2,3])

Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
a = np.array([1, 2, 3])
arr1 = np.repeat(a, 3)
arr2 = np.tile(a, 3)
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Câu hỏi 11. Làm thế nào để lấy các mục chung giữa hai mảng numpy python?
Ví dụ: 
Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

        b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: array([2, 4])

In [2]:
a = np.random.randint(1, 10, size=10)
b = np.random.randint(1, 10, size=10)
a_unique = np.unique(a)
b_unique = np.unique(b)
arr = np.intersect1d(a_unique, b_unique)
print(a)
print(b)
print(arr)

[8 1 2 7 4 9 9 6 7 4]
[5 8 4 8 6 2 2 8 1 4]
[1 2 4 6 8]


In [5]:
a = np.random.randint(1, 10, size=10)
b = np.random.randint(1, 10, size=10)
a_unique = np.unique(a)
b_unique = np.unique(b)

a_remove = np.setdiff1d(a_unique, b_unique)
arr_bool = ~np.isin(a_unique, a_remove)
arr = a_unique[arr_bool]
print(a)
print(b)
print(arr)

[2 9 4 4 3 4 9 4 2 6]
[3 8 4 5 4 2 7 3 3 6]
[2 3 4 6]


### Câu hỏi 12. Làm thế nào để xóa khỏi một mảng những mục tồn tại trong mảng khác? 
Ví dụ: Input: a = np.array([1,2,3,4,5])

              b = np.array([5,6,7,8,9])

Output: array([1,2,3,4])

In [11]:
a = np.random.randint(1, 10, size=10)
b = np.random.randint(1, 10, size=10)

a_unique = np.unique(a)
b_unique = np.unique(b)

a_remove = np.intersect1d(a_unique, b_unique)
arr_bool = ~np.isin(a_unique, a_remove)
arr = a_unique[arr_bool]
print(a)
print(b)
print(arr)

[7 2 9 8 8 2 3 1 2 1]
[1 1 5 4 7 1 9 5 2 9]
[3 8]


### Câu hỏi 13. Làm thế nào để lấy các vị trí mà các phần tử của hai mảng khớp nhau?

Ví dụ: 

Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

       b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: (array([1, 3, 5, 7]),)

In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

arr_bool = (a == b)

arr_index = np.where(arr_bool == True)[0]
print(arr_index)

[1 3 5 7]


### Câu hỏi 14. Làm thế nào để trích xuất tất cả các số trong một phạm vi nhất định từ một mảng numpy?

Ví dụ: 
Input: a = np.array([2, 6, 1, 9, 10, 3, 27])

Output: (array([6, 9, 10]),)

In [24]:
a = np.random.randint(1, 10, size=10)

a_unique = np.unique(a)

arr_condition = ((6 <= a_unique) & (a_unique <= 10))

arr = a_unique[arr_condition]
print(a)
print(arr)

[5 5 4 6 9 5 8 7 3 6]
[6 7 8 9]


### Câu hỏi 16. Làm thế nào để hoán đổi hai cột trong một mảng numpy 2 chiều? 

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Mảng gốc:")
print(arr)

arr[:, [0, 1]] = arr[:, [1, 0]]

print("\nMảng sau khi hoán đổi cột 0 và 1:")
print(arr)

Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mảng sau khi hoán đổi cột 0 và 1:
[[5 2 3]
 [4 1 6]
 [7 8 9]]


### Câu hỏi 17. Làm thế nào để hoán đổi hai hàng trong một mảng numpy 2 chiều? 

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Mảng gốc:")
print(arr)

arr[[0, 1], :] = arr[[1, 0], :]

print("\nMảng sau khi hoán đổi cột 0 và 1:")
print(arr)

### Câu hỏi 18. Làm thế nào để đảo ngược các hàng của một mảng 2 chiều? 

In [3]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Mảng gốc:")
print(arr)

arr_reversed_rows = arr[::-1, :]
print("\nMảng sau khi đảo ngược thứ tự các hàng:", arr_reversed_rows)

Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mảng sau khi đảo ngược thứ tự các hàng: [[7 8 9]
 [4 5 6]
 [1 2 3]]


### Câu hỏi 19. Làm thế nào để đảo ngược các cột của một mảng 2 chiều?

In [4]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Mảng gốc:")
print(arr)

arr_reversed_cols = arr[:, ::-1]
print("\nMảng sau khi đảo ngược thứ tự các hàng:", arr_reversed_cols)

Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mảng sau khi đảo ngược thứ tự các hàng: [[3 2 1]
 [6 5 4]
 [9 8 7]]


### Câu hỏi 20. Làm thế nào để tạo một mảng 2 chiều chứa các số thực ngẫu nhiên giữa 5 và 10?

In [6]:
arr = np.random.randint(5, 11, size=(4, 5))

print(arr)

[[ 9  9  6 10  7]
 [ 9 10  6  6 10]
 [ 6  7 10  8  7]
 [ 5  9  7  8  5]]


### Câu hỏi 21. Làm thế nào để chỉ in 3 chữ số thập phân trong mảng numpy python? 

In [11]:
arr = np.random.uniform(1, 10, size=(4, 5))
print(arr)

arr_round = np.round(arr, 3) 
print(arr_round)

[[3.17597782 4.4236583  3.28637615 1.85140502 4.7369016 ]
 [9.36604012 8.70525513 6.42473843 7.83541727 6.00686302]
 [4.47314709 5.09343421 4.55121849 6.81718178 6.85090308]
 [9.75485474 4.61734632 4.78086313 8.79903353 7.8381574 ]]
[[3.176 4.424 3.286 1.851 4.737]
 [9.366 8.705 6.425 7.835 6.007]
 [4.473 5.093 4.551 6.817 6.851]
 [9.755 4.617 4.781 8.799 7.838]]


### Câu hỏi 22. Làm thế nào để in đẹp một mảng numpy bằng cách loại bỏ ký hiệu khoa học (như 1e10)? 

In [19]:
arr = np.array([1.23e10, 4.56e-5, 1.23456789e4])

print(np.array2string(arr, formatter={'float_kind':lambda x: f"{x:.6f}"}))

[12300000000.000000 0.000046 12345.678900]


### Câu hỏi 24. Làm thế nào để in toàn bộ mảng numpy mà không cần cắt bớt

In [4]:
arr = np.arange(1000)

np.set_printoptions(threshold=np.inf)
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

### Câu hỏi 28. Làm thế nào để tính giá trị trung bình, trung vị, độ lệch chuẩn của một mảng numpy?

In [ ]:
arr = np.arange(1, 21)


m = np.mean(arr)
print("Giá trị trung bình: ", m)

me = np.median(arr)
print("Giá trị trung vị: ", me)

s = np.std(arr)
print("Giá trị độ lệch chuẩn: ", s)

Giá trị trung bình:  10.5
Giá trị trung vị:  10.5
Giá trị độ lệch chuẩn:  5.766281297335398
Giá trị phương sai:  33.25


### Câu hỏi 29. Làm thế nào để chuẩn hóa một mảng sao cho các giá trị nằm chính xác trong khoảng từ 0 đến 1?

In [7]:
arr = np.random.randint(1, 100, size=20)
print("Mảng ban đầu: ", arr)

arr_min = np.min(arr)
arr_max = np.max(arr)
print("Giá trị nhỏ nhất: ", arr_min)
print("Giá trị lớn nhất: ", arr_max)

arr_normalized = (arr - arr_min) / (arr_max - arr_min)
print("Mảng sau khi chuẩn hóa: ", arr_normalized)

Mảng ban đầu:  [57 46 32 10 78 57 51 95 48 51 24 86 74 97 70 83 80 43 72 69]
Giá trị nhỏ nhất:  10
Giá trị lớn nhất:  97
Mảng sau khi chuẩn hóa:  [0.54022989 0.4137931  0.25287356 0.         0.7816092  0.54022989
 0.47126437 0.97701149 0.43678161 0.47126437 0.16091954 0.87356322
 0.73563218 1.         0.68965517 0.83908046 0.8045977  0.37931034
 0.71264368 0.67816092]


### Câu hỏi 30. Làm thế nào để tính điểm softmax?

In [8]:
arr = np.random.randint(1, 5, size=5)
print("Mảng ban đầu: ", arr)

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

arr_softmax = softmax(arr)
print("Mảng sau khi áp dụng hàm softmax: ", arr_softmax)

Mảng ban đầu:  [3 3 4 3 1]
Mảng sau khi áp dụng hàm softmax:  [0.17083454 0.17083454 0.46437643 0.17083454 0.02311994]


### Câu hỏi 32. Làm thế nào để chèn các giá trị ở các vị trí ngẫu nhiên trong một mảng?

Ví dụ: Chèn giá trị 0 vào 20 vị trí ngẫu nhiên trong tập dữ liệu a

In [10]:
import random as r
arr = np.random.randint(1, 100, size=5)
print("Mảng ban đầu: ", arr)

arr = np.insert(arr, r.randint(0, len(arr)), 0)
print("Mảng sau khi chèn giá trị 0: ", arr)

arr = np.insert(arr, r.randint(1, len(arr)), 20)
print("Mảng sau khi chèn giá trị 20: ", arr)

Mảng ban đầu:  [67 92 52 69 99]
Mảng sau khi chèn giá trị 0:  [67 92  0 52 69 99]
Mảng sau khi chèn giá trị 20:  [67 92  0 52 20 69 99]


### Câu hỏi 34. Làm thế nào để lọc một mảng numpy dựa trên hai hoặc nhiều điều kiện?

Ví dụ: Lọc các hàng của a có các giá trị của (cột thứ 3) > 1,5 và các giá trị (cột thứ 1) < 5,0

In [33]:
arr = np.random.randint(1, 7, size=20).reshape(4, 5)
print(arr)

arr_bool = (arr[:, 0] < 5) & (arr[:, 2] > 1.5)

arr_filtered = arr[arr_bool, :]
print(arr_filtered)


[[4 5 5 6 5]
 [4 2 3 2 3]
 [1 1 2 6 4]
 [6 1 5 5 1]]
[[4 5 5 6 5]
 [4 2 3 2 3]
 [1 1 2 6 4]]


### Câu hỏi 36. Làm thế nào để tìm mối tương quan giữa hai cột của mảng numpy?

In [35]:
data = np.array([
    [1, 2],
    [2, 4],
    [3, 6],
    [4, 8]
])

x = data[:, 0]
y = data[:, 1]

corr_matrix = np.corrcoef(x, y)
corr = corr_matrix[0, 1] 

print("Ma trận tương quan:")
print(corr_matrix)
print(f"Hệ số tương quan: {corr:.4f}")


if np.isclose(corr, 1.0, atol=1e-6):
    print("Hai cột có tương quan tuyến tính dương hoàn hảo.")
elif np.isclose(corr, -1.0, atol=1e-6):
    print("Hai cột có tương quan tuyến tính âm hoàn hảo.")
elif abs(corr) >= 0.7:
    print("Hai cột có tương quan tuyến tính mạnh.")
elif abs(corr) >= 0.3:
    print("Hai cột có tương quan tuyến tính yếu.")
else:
    print("Hai cột không có tương quan tuyến tính.")

Ma trận tương quan:
[[1. 1.]
 [1. 1.]]
Hệ số tương quan: 1.0000
Hai cột có tương quan tuyến tính dương hoàn hảo.


### Câu hỏi 44. Làm thế nào để sắp xếp một mảng 2D theo một cột

In [37]:
arr = np.random.randint(1, 100, size=(5, 3))
sorted_by_col0 = arr[arr[:, 0].argsort()]
print("Sắp xếp theo cột 0:\n", sorted_by_col0)

sorted_by_col1 = arr[arr[:, 1].argsort()]
print("Sắp xếp theo cột 1:\n", sorted_by_col1)

Sắp xếp theo cột 0:
 [[11 30 68]
 [22 60 34]
 [34 63 54]
 [82 77 67]
 [86 14  6]]
Sắp xếp theo cột 1:
 [[86 14  6]
 [11 30 68]
 [22 60 34]
 [34 63 54]
 [82 77 67]]


### Câu hỏi 45. Làm thế nào để tìm giá trị thường xuyên nhất trong một mảng numpy?

In [43]:
arr = np.random.randint(1, 10, size=10)
print("Mảng ban đầu:", arr)

unique_vals, counts = np.unique(arr, return_counts=True)
print("Giá trị duy nhất:", unique_vals)
print("Số lần xuất hiện:", counts)

max_count = np.max(counts)
vals_max_count_bool = counts == max_count
vals_max_count = unique_vals[vals_max_count_bool]
print("Giá trị xuất hiện nhiều nhất:", vals_max_count)
print("Số lần xuất hiện:", max_count) 

Mảng ban đầu: [8 9 1 2 7 7 6 5 3 5]
Giá trị duy nhất: [1 2 3 5 6 7 8 9]
Số lần xuất hiện: [1 1 1 2 1 2 1 1]
Giá trị xuất hiện nhiều nhất: [5 7]
Số lần xuất hiện: 2


### Câu hỏi 47. Làm thế nào để thay thế tất cả các giá trị lớn hơn một giá trị nhất định thành một ngưỡng nhất định?

Ví dụ: Từ mảng a, thay thế tất cả các giá trị lớn hơn 30 đến 30 và nhỏ hơn 10 đến 10.

In [ ]:
a = np.array([5, 12, 25, 35, 50])

# Áp dụng ngưỡng: nhỏ hơn 10 → 10, lớn hơn 30 → 30
a_clipped = np.clip(a, 10, 30)

print("Mảng ban đầu:", a)
print("Mảng sau khi giới hạn:", a_clipped)

### Câu hỏi 48. Làm thế nào để lấy vị trí của n giá trị hàng đầu từ một mảng numpy?

Ví dụ: Lấy vị trí của 5 giá trị lớn nhất trong một mảng cho trước a.

In [46]:
a = np.random.randint(1, 10, size=10)
top_n_indices = np.argsort(a)[-5:][::-1]

top_n_values = a[top_n_indices]
print("Mảng ban đầu:", a)
print("5 giá trị lớn nhất:", top_n_values)
print("Chỉ số của 5 giá trị lớn nhất:", top_n_indices)



Mảng ban đầu: [8 1 7 1 7 6 9 4 2 8]
5 giá trị lớn nhất: [9 8 8 7 7]
Chỉ số của 5 giá trị lớn nhất: [6 9 0 4 2]


### Câu hỏi 50. Làm thế nào để chuyển đổi một mảng các mảng thành một mảng phẳng 1 chiều?

In [47]:
a = np.random.randint(1, 10, size=(5, 5))
print("Mảng ban đầu:\n", a)
a = a.reshape(25)
print(a)

Mảng ban đầu:
 [[4 8 8 3 3]
 [1 4 6 4 6]
 [1 3 5 2 5]
 [2 9 9 4 5]
 [6 3 4 2 1]]
[4 8 8 3 3 1 4 6 4 6 1 3 5 2 5 2 9 9 4 5 6 3 4 2 1]


In [48]:
a = np.random.randint(1, 10, size=(5, 5))
print("Mảng ban đầu:\n", a)
a = a.ravel()
print(a)

Mảng ban đầu:
 [[8 3 8 5 9]
 [7 8 1 2 5]
 [6 8 7 7 2]
 [3 9 5 5 6]
 [7 5 9 2 8]]
[8 3 8 5 9 7 8 1 2 5 6 8 7 7 2 3 9 5 5 6 7 5 9 2 8]
